### ISSUE TITLE
OS 10.10

### ISSUE THREAD

**Issue by dxdr** [szhu/fix-growlvoice#6]
Doesn't seem to work under 10.10

**Comment by szhu** [comment]
Since [d235j/GVFixer](https://github.com/d235j/GVFixer) seems to not be giving anyone any problems, this project will be retired.

Also, I am aware that if you have enabled the "send SMS via Hangouts" option, GrowlVoice will no longer show your texts. You can install the [Google Hangouts extension for Google Chrome](https://chrome.google.com/webstore/detail/hangouts/nckgahadagoaajjgafhacjanaoiihapd) to use Hangouts (which will include your texts) without having Gmail/Inbox/Google+ open.
